### ISSUE TITLE
1. 개발자의 자세

### ISSUE THREAD

**Issue by ParkDaeShin** [OHLPstudy/Main#3]
첫 스터디 발표라 어떤 주제로 할지, 프론트와 백엔드 중 어디에 중점으로 할지 생각하다가 생각의 정리를 하다 태초마을로 오게 되어 나의 현재 직업부터 생각하게 되었습니다.

오늘 발표 할 주제는 바로 ‘개발자’ 입니다.

나는 왜 이 직업을 가지게 되었는가? 

개발자란 무엇일까?

나는 어떤 개발자가 되고 싶은가?

개발자가 갖춰야 할 자세는?

앞으로의 계획?

등등 이런 저런 생각을 해봤는데 제가 던진 질문에 대해서 같이 생각해보고 답변하는 시간이 되면 좋겠습니다.

## 1. 개발자 직업을 가지게 된 계기

제가 직업을 정한 이야기는 바야흐로 대학교 3학년 겨울, 2019년이죠 

코로나와 같이 대학 생활을 했습니다. 많은 사람의 목숨을 가져간 무서운 바이러스죠

4학년이 되면서 고민을 했어요. 저는 전공이 전자공학과 이고 학점도 나쁘지 않았어요 3.98 학점이거든요

반도체에 흥미가 없어서 부전공으로 소프트웨어를 선택했는데 회로를 만지다가 코딩을 시작했는데 나쁘지 않았고 당시 대학교 졸업 선배인 ㄱㄱㅂ 을 만나게 되면서 취업을 빨리 하고 싶어 이쪽 길을 걷게 되었습니다

  

그래서 2021년 저는 개발자의 길을 걷게 되었습니다. 근데 개발자란 무엇일까요? 

나무 위키로 개발자를 검색하면 연관된 직업이 나오는데요 

프로그램(program)은 라틴어 ‘미리 쓴다’에서 유래되었고 컴퓨터를 실행시키기 위해 작성된 명령어 모음이 프로그램이라고 이해하면 됩니다.

프로그래머(programer)는 컴퓨터 프로그램의 논리나 알고리즘을 설계하고 프로그램을 작성하고 테스트하는 사람 입니다.

## 2. 나는 어떤 개발자 인가?

이 중 저희는 어떤 직업에 해당 될까요?? 크게 보면 웹 개발자고 더 구체적으로 말 하면 프론트 개발자, 퍼블리셔, 백엔드 개발자, 풀 스택 개발자가 되겠죠?

그러면 나는 프론트, 백엔드, 풀 스택 개발자 중 어떤 개발자일까?? 라는 생각이 들더라고요 

react로 화면을 만드니까 프론트 개발자? java를 이용해서 api 호출 하고 DB에서 데이터를 가져오니 백엔드 개발자?? 난 둘 다 조금 하고 있으니 풀 스택 개발자???

프론트와 백엔드를 다 하고 있지만 아직은 어떤 개발자라고 말하기 애매 해서 이번 기회에 

‘나는 어떤 개발자가 되겠다’ 뱡향성을 천천히 정해보려고 합니다. 

## 3. 개발자가 갖춰야 할 자세는??

검색 하다 이런 생각을 항상 다짐해야겠다 생각되는 것을 몇 개 추려봤는데요

1. **항상 의문을 제기하세요.**
    
    모든 일에 의문을 제기하고 그 의문을 해결하기 위해 지식을 구하고 공부하고 노력하는 것입니다. 여러 블로그를 봤는데 딱 이 문구가 눈에 띄더라고요
    
    ***명심하세요. 세상 어디에도 바보 같은 질문은 없습니다.***
    
2. **긍정적으로 생각하세요.**
    
    개발자는 문제를 해결하는 사람입니다. 일이 어렵고 잘 안 풀리고 부정적으로 생각하는 경우가 많은데 문제가 해결되지 않는다면 결국 얻을 수 있는 것은 없습니다. 
    
    개발자는 문제를 기술을 통해 해결하는 사람입니다.
    
3. **의사소통은 말로 하세요.**
    
    개발자는 코드로 말한다고 굳게 믿는 엔지니어들이 있습니다. 일리는 있지만, 
    
    좋은 개발자는 말로 의사소통을 한다고 생각합니다.
    
    소프트웨어 개발이란 팀 플레이이고, 중요한 건 자신의 코드가 남들보다 뛰어난 것이 아니라 
    
    팀이 우수한 서비스를 제공할 수 있게 서포트 하는 것입니다. 협업이란 대화입니다.
    
4. **항상 겸손하세요.**
    
    마지막으로 가장 중요한 태도입니다. 
    
    특히 뛰어난 개발자일수록 자존감이 높은 엔지니어들이고, 오만해지기 쉽습니다. 
    
    하지만 대부분의 개발은 협업이고, 모든 비즈니스는 일종의 커뮤니케이션입니다. 
    
    자존감이 높아졌다고, 오만하게 행동 하는 건 좋은 자세가 아닙니다.
    

## 4. 앞으로의 계획?

기능을 직접 구현 하는것도 중요하지만 지금 제 상황을 보면 기초, 이론부터 다시 시작하며 

설명 할 수 있을 정도가 되어야 한다고 생각합니다.

프로젝트를 하면서 새로운 경험, 지식을 얻긴 했지만 막상 설명하라고 하면 설명하기 어렵고, 

머리 속에 남는게 별로 없더라고요.

그래서 생각한게 면접에 많이 나오는 개념, 기술을 중점으로 두고 공부하려고 합니다.

프론트, 백엔드 구분 없이 면접에 자주 나오는 질문 list를 정리하고 하나씩 개념과 원리에 대해서 

파악 후 소스로 적용 할 수 있는 부분은 github에 올릴 예정입니다

회사에서 일 하던 도중 새로운 걸 하거나 이슈를 해결한 방법을 간단히 정리도 하면서 

제가 경험하고 궁금한 것을 정리하려고 합니다.

제가 준비하고 조사한 내용이 부정확하고 빠트린 내용이 있을 수 있습니다.

이상하거나 빠진 내용이 있으면 편하게 말 해주시면 좋을 거 같아요.

## 5. 마치며

발표 준비를 하다 보니 어떤 개발자가 될 것 인가에 대한 질문에 방향성을 조금 잡고 

어떻게 준비 할 것 인가에 대한 힌트를 조금 얻었는데요

저는 직업으로는  프론트, 백엔드 구분 없이 하는 풀 스택 개발자를 목표로 하고

되고 싶은 개발자는 ‘Run 하는 개발자’ 입니다

Run은 **컴퓨터가 이해하지 못하는 소스 코드를 이해할 수 있는 기계어로 바꿔** 

**하드웨어의 OS에 맞게 실행하는 것** 을 의미하는데요 

개념과 원리를 이해하고 사용하는 개발자가 되자는 뜻 입니다.

**Comment by lso5507** [comment]
회고록 잘 읽었습니다!
저도 요새 누구나 찾아오는 번아웃이 가끔 찾아오는데, 그 이유는 개발공부가 질려서 인경우가 많은 것 같습니다.
개념과 원리를 이해하는 개발자 되려면 학습방법도 중요하다고 생각이 드는데 대신씨가 생각하는 올바른 학습법이 따로 있나요?

**Comment by ParkDaeShin** [comment]
감사합니다. 제가 생각 했을때는 정리도 중요하지만 반복적인 학습이 좋은거 같습니다. 단순히 시험을 위한, 발표를 를 위한 자료가 아니라 누가 질문하면 바로 나올 수 있을 정도로 반복 학습이 중요시 된다 생각합니다.
