### ISSUE TITLE
1. HTTP #1

### ISSUE THREAD

**Issue by ohdanini** [OHLPstudy/Main#4]
이번 주제는 우리가 개발하면서 자주 마주하는 HTTP 관련 개념에 대해 이야기해 보겠습니다.

이 주제를 선택한 이유는 개발을 하면서 자주 마주하게 되는 개념이지만 명확하게 아는 것이 없어, 이번 기회에 확실하게 공부해 보고자 했기 때문입니다. 특히, 상태 코드 같은 경우는 매번 검색하던 제 모습을 떠올리며, 이번에는 확실하게 알아보자는 마음으로 공부해 보았습니다.

## 1. HTTP란?

1. HTTP 개념
    
    HTTP는 HyperText Transfer Protocol의 약자로, 클라이언트와 서버 간에 데이터를 주고받는 표준 프로토콜입니다. 주로 웹 페이지와 같은 리소스를 전송하는 데 사용됩니다. 클라이언트는 서버에게 요청을 보내고, 서버는 클라이언트에게 요청한 데이터를 응답으로 보내 줍니다. 간단히 말해서, 웹 브라우저가 웹 서버와 통신하는 방식을 말합니다.
    
2. HTTP 쓰임새
    - HTML, TEXT, IMAGE, 음성, 영상, 파일, JSON, XML (API) 등 거의 모든 형태의 데이터 전송이 가능합니다.
    - 서버 간에 데이터를 주고받을 때도 대부분 HTTP를 사용합니다.
3. HTTP 간략한 역사
    - HTTP는 1991년에 HTTP/0.9 버전으로 처음 등장했습니다. 이후 여러 차례 개선되어 현재 HTTP/2와 HTTP/3 버전까지 나왔습니다.

## 2. HTTP 특징

앞서 말씀드렸다시피, HTTP는 클라이언트와 서버 간의 요청-응답 방식으로 작동합니다. 클라이언트는 보통 웹 브라우저를 말하고, 서버는 웹 사이트를 호스팅하는 컴퓨터입니다. 클라이언트가 특정 웹 페이지를 요청하면 서버가 그 페이지를 응답으로 보내 주는 방식입니다.

1. 클라이언트 서버 구조
    
    ![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/5acd76f4-c396-45b0-9dd0-0f39ee72bbee/b0c3d1e6-fca2-418d-a732-b18510a79c0e/Untitled.png)
    
    - HTTP는 클라이언트-서버 모델을 기반으로 합니다.
    - 클라이언트는 서버에 요청을 보내고 응답을 대기합니다.
    - 서버는 요청에 대한 결과를 만들어서 응답합니다.
    - 이 구조는 서로 독립적으로 동작하며, 상호작용하는 웹 애플리케이션을 구축하는 데 중요합니다.
2. 무상태 프로토콜 (Stateless)
    - HTTP는 상태를 유지하지 않는 Stateless 프로토콜로, 각 요청이 서로 독립적으로 처리됩니다.
    - 갑자기 클라이언트 요청이 증가하거나, 중간에 서버 장애가 일어나도 다른 서버에서 응답할 수 있습니다.
    - 서버가 클라이언트의 상태를 유지하지 않기 때문에 서버의 확장성이 높습니다.
    - 최소한의 상태는 필요한데, 예를 들어 로그인 상태를 유지하기 위해 세션 및 쿠키를 사용할 수 있습니다.
3. 비 연결성 (Connectionless)
    - HTTP는 요청과 응답 간에 연결을 유지하지 않습니다.
    - 각 요청이 독립적으로 처리되어 서버의 부하를 줄이는 데 도움이 됩니다.
    - 이를 해결하기 위해 HTTP 지속 연결을 사용하여 여러 요청/응답이 하나의 TCP 연결을 통해 처리할 수 있습니다.
4. HTTP 메시지
    - HTTP 메시지는 요청(Request)과 응답(Response)를 구성됩니다. 이는 헤더와 바디로 나뉘며, 헤더는 메시지의 메타데이터를 포함하고, 바디에는 실제 데이터가 포함됩니다.
    - **헤더(Header)**: 요청이나 응답의 메타데이터를 포함합니다.
        - 일반 헤더, 요청 헤더, 응답 헤더, 엔티티 헤더 등이 있습니다.
    - **바디(Body)**: 요청이나 응답의 실제 데이터를 포함합니다.
        - 예: HTML 문서, JSON 데이터, 이미지 등

## 3. HTTP 메서드

HTTP 요청에는 여러 가지 메서드가 있으며, 메서드는 서버에 특정한 작업을 요청합니다.

개발 시 이 메서드를 어떻게 활용하는지 매우 중요합니다.

대표적인 메서드를 소개하도록 하겠습니다.

1. GET
    - 서버로부터 데이터를 가져옵니다. 예를 들어, 특정 웹 페이지를 요청할 때 사용됩니다.
    - 예시: `GET /index.html HTTP/1.1`
2. POST
    - 서버에 데이터를 제출합니다. 주로 사용자가 입력한 데이터를 서버로 전송할 때 사용됩니다.
    - 예시: `POST /submit-form HTTP1/1.1`
3. PUT
    - 리소스를 생성하거나 업데이트합니다. 전체 리소스를 대체합니다.
    - 예시: `PUT /users/123 HTTP/1.1`
4. PATCH
    - 리소스의 일부를 수정합니다. 예를 들어, 프로필 이미지를 변경하거나 일부 정보를 수정할 때 사용됩니다.
    - 예시: `PATCH /users/123 HTTP/1.1`
5. DELETE
    - 리소스를 삭제합니다.
    - 예시: `DELETE /users/123 HTTP/1.1`

### 4. HTTP 메서드 속성 및 활용

1. 클라이언트에서 서버로 데이터 전송 방법
    - 쿼리 파라미터를 통한 데이터 전송
        - GET
        - 주로 정렬 필터 (검색어)
    - 메시지 바디를 통한 데이터 전송
        - POST, PUT, PATCH
        - 회원가입, 상품 주문, 리소스 등록, 리소스 변경
2. 클라이언트에서 서버로 데이터 전송 4가지 상황
    - 정적 데이터 조회
        - 이미지, 정적 텍스트 문서
        - 조회는 GET
        - 일반적으로 쿼리 파라미터 없이 리소스 경로로 단순하게 조회 가능
    - 동적 데이터 조회
        - 주로 검색, 게시판 목록에서 정렬 필터 (검색어)
        - 조회는 GET
        - GET은 쿼리 파라미터 사용해서 데이터 전달
    - HTML Form을 통한 데이터 전송
        - 회원가입, 상품주문, 데이터 변경
        - POST 전송 - 저장
        - GET 전송도 가능
    - HTML API를 통한 데이터 전송
        - 회원가입, 상품주문, 데이터 변경
            
            ![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/5acd76f4-c396-45b0-9dd0-0f39ee72bbee/a01a1f7c-ee54-48ac-96e8-bea44d9de79c/Untitled.png)
            

## 5. HTTP 상태 코드

1. HTTP 상태 코드 소개
    - HTTP 상태 코드는 클라이언트가 보낸 요청에 대한 서버의 응답을 나타냅니다. 이는 클라이언트에게 요청의 결과를 전달하는 중요한 수단입니다.
2. 1xx - 정보
    - 요청을 받았고 처리가 진행 중임을 나타냅니다.
    - 거의 사용하지 않습니다.
3. 2xx - 성공
    - 요청이 성공적으로 처리되었음을 나타냅니다.
    - `200 OK`: 요청이 성공적으로 처리되었습니다.
    - `201 Created`: 요청이 성공적으로 처리되었으며, 새로운 리소스가 생성되었습니다.
        
        ![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/5acd76f4-c396-45b0-9dd0-0f39ee72bbee/5436e4a4-3c60-4be2-b5d7-791494cb1b98/Untitled.png)
        
    - `202 Accepted`: 요청이 접수되었으나 처리가 완료되지 않았습니다. 주로 배치 처리 같은 곳에서 사용됩니다. 요청 접수 후 한 시간 뒤 배치 프로세스가 요청을 처리함.
    - `204 No Content` : 서버가 요청을 성공적으로 수행했지만, 응답 페이로드 본문에 보낼 데이터가 없습니다. 결과 내용이 없어도 204 메시지(2xx)만으로 성공을 인식할 수 있습니다. 예를 들어서 웹 문서 편집기에서 Save 버튼을 눌렀을 때 나타납니다. 버튼의 결과로 아무 내용이 없어도 되며, 같은 화면을 유지해야 합니다.
4. 3xx - 리다이렉션
    - 리다이렉션을 나타냅니다.
    - 클라이언트가 요청한 리소스가 다른 위치에 있거나 추가 동작이 필요할 때 사용됩니다.
    - `301 Moved Permanently`: 요청한 리소스가 영구적으로 새로운 위치로 이동되었습니다.
    - `302 Found`: 요청한 리소스가 임시로 다른 위치에 있습니다.
    - 더보기
        - 웹 브라우저는 3xx 응답 결과에 Location 헤더가 있으면, 해당 Location 위치로 자동으로 이동합니다. 이것을 리다이렉트라고 합니다.
            
            ![Untitled](https://prod-files-secure.s3.us-west-2.amazonaws.com/5acd76f4-c396-45b0-9dd0-0f39ee72bbee/b95418bf-1061-4914-bac5-683816686377/Untitled.png)
            
        - 리다이렉션 종류
            - 영구 리다이렉션 (301, 308)
                - 특정 리소스의 URI가 영구적으로 이동
                - 원래의 URL을 사용하지 않으며, 검색 엔진 등에서도 변경 인지
                - `301 Moved Permanentl` : 메서드가 GET으로 변하고 본문이 제거될 수 있음
                - `308 Permanent Redirect` : 301과 기능은 같으나, 리다이렉트 요청 시 메서드와 본문 유지 (처음 POST를 보내면 리다이렉트도 POST 유지)
            - 일시 리다이렉션 (302, 307, 303)
                - 리소스의 URI 일시적으로 변경
                - 따라서 검색 엔진 등에서 URL 변경하면 안 됨
                - 예시: 주문 완료 후 주문 내역 화면으로 이동 (POST → GET)
                - `302 Found` : 메서드가 GET으로 변하고, 본문이 제거될 수 있음
                - `307 Temporary Redirect` : 302와 기능은 같으나, 요청 메서드와 본문 유지
                - `303 See Other` : 302와 기능은 같음, 요청 메서드가 GET으로 변경
            - 특수 리다이렉션 (300, 304)
                - `300 Multiple Choices` : 안 씀
                - `304 Not Modified`: 결과 대신 캐시를 이용
5. 4xx - 클라이언트 오류
    - 클라이언트 측의 오류를 나타냅니다.
    - 주로 잘못된 요청이나 권한 부족 등의 이유로 발생합니다.
    - 클라이언트가 이미 잘못된 요청, 데이터를 보내고 있기 때문에 똑같은 상황으로 재시도 해도 실패합니다.
    - 예를 들어서 서버에서는 int인데 클라이언트에서 String으로 입력하는 것처럼  잘못된 문법으로 발생합니다.
    - `400 Bad Request`: 클라이언트가 잘못된 요청을 해서 서버가 요청을 처리할 수 없습니다.
        - 요청 구문, 메시지 등 오류
        - 요청 파라미터 문제 또는 API 스펙 불일치
    - `401 Unauthorized`: 클라이언트가 해당 리소스에 대한 인증이 필요합니다.
        - 인증이 되지 않음
        - 401 오류 발생 시 응답에 WWW-Authenticate 헤더와 함께 인증 방법 설명
    - `403 Forbidden`: 서버가 요청을 이해했지만 승인을 거부했습니다.
        - 주로 인증 자격 증명은 있지만, 접근 권한이 불충분한 경우
        - 예시: admin 등급이 아닌 사용자가 로그인은 했지만, admin 등급의 리소스에 접근하는 경우
    - `404 Not Found`: 요청한 리소스를 찾을 수 없습니다.
        - 또는 클라이언트가 권한이 부족한 리소스에 접근할 때 해당 리소스를 숨기고 싶을 때
6. 5xx - 서버 오류
    - 서버 측의 오류를 나타냅니다.
    - 서버가 요청을 처리하는 동안 예상치 못한 오류가 발생한 경우에 사용됩니다.
    - 서버 장애, 디비 장애 등 서버에서 복구 가능한 문제이기 때문에 클라이언트가 재시도 하면 성공할 수 있습니다.
    - `500 Internal Server Error`: 서버에서 문제가 발생하였습니다.
        - 서버 내부 문제로 오류 발생
    - `502 Bad Gateway`: 서버가 잘못된 응답을 받았습니다.
    - `503 Service Unavailable`: 서버가 일시적으로 사용 불가능합니다.
        - 서버가 일시적인 과부하 또는 예정된 작업으로 잠시 요청을 처리할 수 없음
        - Retry-After 헤더 필드로 얼마 뒤에 복구되는지 보낼 수도 있음
7. HTTP 상태 코드 활용
    - 올바른 상태 코드를 사용하면 클라이언트는 요청의 성공 또는 실패를 즉시 파악할 수 있습니다.
    - 각 상태 코드의 의미를 이해하고 상황에 맞게 반환하는 것이 중요합니다. 예를 들어, 리소스가 존재하지 않는 경우 404 상태 코드를 반환하고, 서버에 문제가 있을 때 500 상태 코드를 반환합니다.

**Comment by lso5507** [comment]
간혹 개발을 진행하다 보면 요청에 대한 에러 응답 값으로 body에  stacktrace같은 성격을 띄는 메시지를 포함하여 응답해주는 서버가 있는데,
이 부분은 보안적으로 문제가 없는지랑 문제가 있다면 어떻게 해결할 수 있는지가 궁금하네요.

올려주신 회고록 잘 읽었습니다!
